language: go
sudo: false
go:
  - "1.8"
  - "1.10.x"
  - master
env:
  - CGO_ENABLED=0
script:
  - make
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
    provider: script
    script: build-and-push.sh
    on:
      tags: true
