language: go
sudo: false
matrix:
  include:
    - go: "1.8"
    - go: "1.10.x"
      env:
        - CGO_ENABLED=0
        - FOR_DOCKER=true
    - go: "1.11.x"
env:
  - CGO_ENABLED=0
script:
  - make
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
    provider: script
    skip_cleanup: true
    script: ./build-and-push.sh
    on:
      tags: true
      condition: $FOR_DOCKER = true
